using UnityEngine;
using System.Collections;

public enum AN_LicenseRequestResult {
	RESULT_LICENSED,
	RESULT_RETRY,
	RESULT_NOT_LICENSED,
	ERROR_CHECK_IN_PROGRESS,
	ERROR_INVALID_PACKAGE_NAME,
	ERROR_INVALID_PUBLIC_KEY,
	ERROR_MISSING_PERMISSION,
	ERROR_NON_MATCHING_UID,
	ERROR_NOT_MARKET_MANAGED,
	ERROR_UNKNOWN
}
